languages = {
    ("ACE", "Acehnese"),
    ("AF", "Afrikaans"),
    ("AN", "Aragonese"),
    ("AY", "Aymara"),
    ("AZ", "Azerbaijani"),
    ("BR", "Breton"),
    ("BS", "Bosnian"),
    ("CA", "Catalan"),
    ("CEB", "Cebuano"),
    ("CS", "Czech"),
    ("CY", "Welsh"),
    ("DA", "Danish"),
    ("DE", "German"),
    ("EN-GB", "English (British)"),
    ("EN-US", "English (American)"),
    ("EO", "Esperanto"),
    ("ES", "Spanish"),
    ("ES-419", "Spanish (Latin American)"),
    ("ET", "Estonian"),
    ("EU", "Basque"),
    ("FI", "Finnish"),
    ("FR", "French"),
    ("GA", "Irish"),
    ("GL", "Galician"),
    ("GN", "Guarani"),
    ("HA", "Hausa"),
    ("HR", "Croatian"),
    ("HT", "Haitian Creole"),
    ("HU", "Hungarian"),
    ("ID", "Indonesian"),
    ("IG", "Igbo"),
    ("IS", "Icelandic"),
    ("IT", "Italian"),
    ("JV", "Javanese"),
    ("KMR", "Kurdish"),
    ("LA", "Latin"),
    ("LB", "Luxembourgish"),
    ("LMO", "Lombard"),
    ("LN", "Lingala"),
    ("LT", "Lithuanian"),
    ("LV", "Latvian"),
    ("MG", "Malagasy"),
    ("MI", "Maori"),
    ("MS", "Malay"),
    ("MT", "Maltese"),
    ("NB", "Norwegian Bokmål"),
    ("NL", "Dutch"),
    ("OC", "Occitan"),
    ("OM", "Oromo"),
    ("PAG", "Pangasinan"),
    ("PAM", "Kapampangan"),
    ("PL", "Polish"),
    ("PT-BR", "Portuguese (Brazilian)"),
    ("PT-PT", "Portuguese"),
    ("QU", "Quechua"),
    ("RO", "Romanian"),
    ("SCN", "Sicilian"),
    ("SK", "Slovak"),
    ("SL", "Slovenian"),
    ("SQ", "Albanian"),
    ("ST", "Sesotho"),
    ("SU", "Sundanese"),
    ("SV", "Swedish"),
    ("SW", "Swahili"),
    ("TK", "Turkmen"),
    ("TL", "Tagalog"),
    ("TN", "Tswana"),
    ("TR", "Turkish"),
    ("TS", "Tsonga"),
    ("UZ", "Uzbek"),
    ("VI", "Vietnamese"),
    ("WO", "Wolof"),
    ("XH", "Xhosa"),
    ("ZU", "Zulu"),
}